http:
  routers:
    filebrowser:
      rule: "Host(`fzryzen.local`) && PathPrefix(`/browser`)"
      service: filebrowser-service
      middlewares:
        - common-redirect-to-https

  services:
    filebrowser-service:
      loadBalancer:
        servers:
          - url: "http://fzfilebrowser/browser"
