http:
  routers:
    openwebui:
      rule: "Host(`openwebui.fzryzen.local`)"
      service: openwebui-service
      middlewares:
        - common-redirect-to-https

  services:
    openwebui-service:
      loadBalancer:
        servers:
          - url: "http://fzopenwebui:8080"
