version: '3.9'

services:

  db:
    image: mysql:8.0.30
    container_name: g_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Password#123
    ports:
      - 8893:3306
    # volumes:
    #   - ./.data/mysql:/var/lib/mysql

  guacd:
    image: guacamole/guacd:1.4.0
    container_name: g_guacd
    environment:
      - GUACD_LOG_LEVEL=debug
  
  guacamole:
    image: guacamole/guacamole:1.4.0
    container_name: g_guacamole
    environment:
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
      - MYSQL_HOSTNAME=host.docker.internal
      - MYSQL_PORT=8893
      - MYSQL_DATABASE=guacamole
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Password#123
    depends_on:
      - guacd
      # - db
    ports:
      - 8891:8080

#  adminer:
#    image: adminer
#    container_name: g_adminer
#    depends_on:
#      - db
#    ports:
#      - 8890:8080
