#!/bin/bash

MYSQL_PORT=8893

if [[ ! -z $(mysql -P "${MYSQL_PORT}" -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='guacamole'") ]]; then 
    echo "Already guacamole database present, droping it."
    mysql -P "${MYSQL_PORT}" -e "drop database guacamole"
fi

mysql -P "${MYSQL_PORT}" -e "create database guacamole"

docker exec -it g_guacamole /opt/guacamole/bin/initdb.sh --mysql | mysql -P "${MYSQL_PORT}" -D guacamole


