version: '3.9'

services:
  db:
    image: ubuntu:22.04
    container_name: ubuntu
    command: tail -f /dev/null
    #restart: always
    ports: 
      - 8901:3000
      - 8902:8080
      - 8903:8000
    volumes:
      - ./.data:/root
      - ./config:/root/config
