version: '3.9'

services:
  homeassistant:
    # build: .
    image: homeassistant/home-assistant
    container_name: homeassistant
    ports: 
      - 8123:8123
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      # - ./.config/mosquitto/config:/mosquitto/config
      - ./.data/mosquitto/data:/mosquitto/data
      - ./.data/mosquitto/log:/mosquitto/log
  esphome:
    image: esphome/esphome
    container_name: esphome
    ports:
      - 6052:6052