#!/bin/bash

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
sudo mkdir -p /opt/conda
sudo chown $USER:$USER /opt/conda
bash ~/miniconda.sh  -bup /opt/conda
eval "$(/opt/conda/bin/conda shell.bash hook)"
conda init
rm ~/miniconda.sh

pip install jupyterlab==3.4.6
pip install jupyterlab-git==0.39.2

pip install plotly==5.0.0
pip install -U pycodestyle==2.5.0
pip install -U pylint==2.4.4
pip install dash
pip install ipywidgets
pip install -U databricks-connect==7.3.47
pip install -U dotmap
pip install -U sqlalchemy
pip install -U snowflake-sqlalchemy
pip install psycopg2

