version: '3.9'

services:

  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    #restart: always
    environment:
      JUPYTER_ENABLE_LAB: yes
      GRANT_SUDO: yes
    user: root
    ports: 
      - 7801:8888
      - 7802:5000
      - 7803:8080
    volumes:
      - ./.data:/home/
      #- /Volumes/afzalex/source/fzdockers/jupyter/.data/jovyan:/home/jovyan/macair/
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''


