version: '3.9'

services:
  db:
    build: .
    #image: amazonlinux:2022
    container_name: ec2
    # command: tail -f /dev/null
    #restart: always
    ports: 
      - 8904:3000
      - 8905:8080
      - 8906:8000
      - 8907:22
      - 8908:8888
    volumes:
      # - ./.data:/root/python3.7.3-browser-template-1.0
      # - ./config:/home/ciuser/config
      # - ./.data:/home/ciuser/data
      - /Users/mafzal/source/fzdockers/amazonlinux/.data:/home/ciuser/data
      - /Users/mafzal/source/fzdockers/amazonlinux/config:/home/ciuser/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/mafzal/source:/app/source

