version: '3.9'

services:
  db:
    image: portainer/portainer-ce
    container_name: portainer
    ports: 
      - 9000:9000
    volumes:
      - ./.data:/data
      - ./config:/root/config
      - /var/run/docker.sock:/var/run/docker.sock
