version: '3.9'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      #MYSQL_ROOT_PASSWORD=12345
      #- MYSQL_ALLOW_EMPTY_PASSWORD
      MYSQL_ROOT_PASSWORD: password#123
    ports: 
      - 3306:3306
    volumes:
      - ./.data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8980:8080
