version: '3.9'

services:

  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    container_name: local-mysql
    # restart: always
    environment:
      #MYSQL_ROOT_PASSWORD=12345
      #- MYSQL_ALLOW_EMPTY_PASSWORD
      MYSQL_ROOT_PASSWORD: "Password#123"
    ports: 
      - 3306:3306
    volumes:
      - ./.data/var/lib/mysql:/var/lib/mysql
      - ./.data/var/lib/mysql/backup:/var/lib/mysql

  adminer:
    image: adminer
    container_name: local-adminer
    #restart: always
    ports:
      - 8980:8080
