version: '3.9'

services:

  db:
    # image: coderaiser/cloudcmd
    build: .
    container_name: cloudcmd
    #restart: always
    environment:
      CLOUDCMD_NAME: cloudcmd
    user: root
    ports: 
      - 8000:8000
    volumes:
      - ./.data:/home/
      - /:/mnt


